### ISSUE TITLE
Future date

### ISSUE THREAD

**Issue by whawker** [k-yle/react-timeago-i18n#2]
Hi there, I'm interested in adopting this library over `timeago-react` which we currently use. I like how you're leveraging Intl APIs rather than doing it manually.

However, I notice that future dates are not supported - it [always returns `0 seconds`](https://github.com/k-yle/react-timeago-i18n/blob/main/src/index.ts#L39) if the date is in the future. This would be a key feature for my use case, where I have a list of articles scheduled to publish at a future date.

Would this be something you'd be willing to accept as a PR? Perhaps as an opt-in feature?

Also, would you be willing to accept a custom prop for "now" - so rather than `1 minute` you could pass in something like `['just now', 'right now'] to be displayed instead

**Comment by k-yle** [comment]
Hey, yes PRs would be most welcome :) I also think both your ideas are useful and would be valuable enhancements

**Comment by whawker** [comment]
No worries, I have opened #3
